// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwbYm5i93mZczzemKGK-T2RqbGHo9oCQ',
    appId: '1:738811570166:web:2b31cf6f237ce7591849d7',
    messagingSenderId: '738811570166',
    projectId: 'aquaniti',
    authDomain: 'aquaniti.firebaseapp.com',
    storageBucket: 'aquaniti.appspot.com',
    measurementId: 'G-7WEHS45HHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6tqaTQQr7cXajulT1iUapsUI7U7hZe0Y',
    appId: '1:738811570166:android:b9a5fddb5cc62db01849d7',
    messagingSenderId: '738811570166',
    projectId: 'aquaniti',
    storageBucket: 'aquaniti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjWo_1hN7vC0E3FllgnPn43NSOZuJOOcE',
    appId: '1:738811570166:ios:44a12ff9f3f329301849d7',
    messagingSenderId: '738811570166',
    projectId: 'aquaniti',
    storageBucket: 'aquaniti.appspot.com',
    iosBundleId: 'com.example.aquaniti',
  );
}
